### ISSUE TITLE
Deprecated `@types/dotenv`

### ISSUE THREAD

**Issue by seheon99** [SeoulGreenJacket/Dr.Trash-BE#1]
`dotenv` 에서 타입을 제공해서 `@types/dotenv` 는 필요가 없대요

[@types/dotenv - npm](https://www.npmjs.com/package/@types/dotenv)

**Comment by happyjamy** [comment]
nest configModule 사용시 dotenv library 가 내부적으로 설치된다고 해서 아예 둘다 uninstall 했습니다.
