### ISSUE TITLE
feature: ESlint 설정

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash-BE#16]
## 개발사항

같이 ESlint 설정을 해서 코드 스타일을 맞추어 보아요.
해당 코드 스타일에 맞지 않으면 push 하지 못하게해서 조금 더 코드 스타일 균일화에 도움이 될 것같습니다.
그리고 lint가 제어하지 못하는 나머지 세부적인 부분은 고쳐서 pr 보내주시는 걸로 하면 어떨까요?

**Comment by seheon99** [comment]
좋아요 스타일을 하나 정해서 스타일과 맞지 않으면 저장도 못하게 해요

VSCode 확장 프로그램 `prettier` 로 할 수 있어요

**Comment by seheon99** [comment]
https://github.com/SeoulGreenJacket/Dr.Trash-BE/blob/develop/.prettierrc

스타일은 프리티어로 어느 정도 관리하는 것 같아요
