### ISSUE TITLE
`auth/dto/user.dto.ts` 주석

### ISSUE THREAD

**Issue by seheon99** [SeoulGreenJacket/Dr.Trash-BE#2]
`main` 에 푸시하기 전에 주석은 최대한 지워주세요

https://github.com/SeoulGreenJacket/Dr.Trash-BE/blob/3347e9199e037b4ec03ee6a5a168a8580c47ca8c/src/auth/dto/user.dto.ts#L6-L9

**Comment by happyjamy** [comment]
삭제해쩌욥 ㅠ
