### ISSUE TITLE
DatabaseModule 안에 OnApplicationShutdown 질문!

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash-BE#24]
DatabaseModule 안에 OnApplicationShutdown 는 네스트 종료할때 데이터베이스 연결해제를 제대로 하려고 넣은것 같은데
이거는 도커나 쿠버네틱스 쓸 때 필요해서 넣은건가요?? 넣은 의도가 궁금해요!
![스크린샷 2022-08-15 오후 2 28 07](https://user-images.githubusercontent.com/78072370/184581265-06534117-f038-42e1-b18f-a31646a227d3.png)

**Comment by seheon99** [comment]
도커나 쿠버네티스를 안쓰더라도 `new Pool()` 로 연결을 만들면 `close` 하는걸 권장하고 있어요. `pool.end` 에 대한 설명으로 `pool` 을 사용하는 스크립트의 마지막 또는 어플리케이션이 종료될 때 깔끔하게 종료하기 위해서 일반적으로 사용한다고 해요.

> Calling pool.end will drain the pool of all active clients, disconnect them, and shut down any internal timers in the pool.
> It is common to call this at the end of a script using the pool or when your process is attempting to shut down cleanly.

- [pg.Pool | node-postgres](https://node-postgres.com/api/pool#poolend)

아래는 소켓 통신할 때 `close` 를 해야하는지에 대한 질문글이에요

- [close를 안해서 생기는 문제](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=chhh92&logNo=70158632001)
- [close를 안해주면 문제가 되나요?](https://okky.kr/article/131133)

**Comment by happyjamy** [comment]
당신의 지식에 무릎을 탁 치고 갑니다~👍
