### ISSUE TITLE
인증 레포지토리 삭제

### ISSUE THREAD

**Issue by seheon99** [SeoulGreenJacket/Dr.Trash-BE#29]
`AuthRepository` 를 어디서 사용하고있는지 모르겠어요 삭제하는게 어떨까요

https://github.com/SeoulGreenJacket/Dr.Trash-BE/blob/8d4debc104426a4e6c54b479f8887ef0553a4be2/src/auth/auth.service.ts#L28

https://github.com/SeoulGreenJacket/Dr.Trash-BE/blob/8d4debc104426a4e6c54b479f8887ef0553a4be2/src/auth/auth.service.ts#L56

**Comment by happyjamy** [comment]
이거 토큰 관련해서 쓰는건데 나중에 토큰브렌치에서 한방에 삭제하면 안될깝쇼??

**Comment by seheon99** [comment]
이슈 다시 올릴게요~
