### ISSUE TITLE
토큰 관리 방법 변경

### ISSUE THREAD

**Issue by seheon99** [SeoulGreenJacket/Dr.Trash-BE#30]
JWT service를 사용해서 토큰을 생성하고 passport JWT 전략을 사용해서 토큰 유효성 검사를 진행하겠습니다

**Comment by happyjamy** [comment]
제가 passport 가 토큰 유효성 검사를 잘 해줘서 서버나 캐시에 토큰을 따로 저장 안해도 될 것같다고 했는데
다시 생각해 보니 만약 유저가 로그아웃을 하면 해당 토큰을 만료 시켜 줘야하는데 따로 만료시키는 방법이 없으니
서버에 토큰이나 uuid를 저장해서 대조하는 로직을 하나 더 추가 해야 될 것같아요ㅠㅠ!
해당 로직을 추가 안하면 유저가 토큰을 탈취당한 상태일때 로그아웃을 해도 그 탈취당한 토큰은 계속 쓰일 수 있으니까!!

☝️ 토큰 발급할때 payload에 uuid를 같이 넣어서 validate할때 encode해서 서버에 있는 uuid와 대조하는 방식으로 하는게 어떨까요?

**Comment by seheon99** [comment]
캐시가 로그아웃때문에 있는거군요

토큰을 만들 때 이미 유저아이디가 저장되는데 UUID를 따로 만들 필요가 있을까요?

**Comment by happyjamy** [comment]
근데 그럼 서버에 저장하는 비교군을 유저 아이디로 저장해야되는데, 그럼 토큰 테이블에 유저 아이디를 저장하면 뭔가 이상하지 않나염...?? 로직상으로는 상관 없긴 할 것같아염

**Comment by seheon99** [comment]
여러 브라우저에서 한 아이디로 동시에 로그인하는 경우를 생각하면 uuid를 만들어서 저장하는게 좋을 것 같아요

**Comment by happyjamy** [comment]
오우~ 굳~
