### ISSUE TITLE
userRepository 안에 findIdByOAuth에 대한 질문!

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash-BE#33]
`userRepository` 안에 `findIdByOAuth` 라는 함수는 OAuth 데이터를 가지고 맞는 데이터가 있으면 userId를 반환하는 일을 합니다

```javascript
async findIdByOAuth(oauthId: string, provider: string) {
  const result = await this.databaseService.query<{ userId: number }>(
    `SELECT userId FROM ${this.oauthTable} WHERE oauthId='${oauthId}' AND provider='${provider}';`,
  );
  return result.length === 1 ? result[0].userId : null;
}
```

저는 현재 카카오 전략 중에 유저가 존재하는지 아닌지를 확인해서 
있다면 -> userId 반환
없다면 -> create 후 userId 반환 하는 로직을 작성중인데
이때 `userRepository` 안에 `findIdByOAuth` 함수를 쓰거든요.

```javascript
const existedUser: number = await this.usersRepository.findIdByOAuth(
  oauthId,
  provider,
);
if (existedUser) {
  return existedUser;
} else {
  const userId: number = await this.userService.create(
    oauthId,
    provider,
    thumbnail,
    name,
  );
  return userId;
}
```

근데 이 `findIdByOAuth` 함수는 그냥 oauth table에 있는 userId 라는 컬럼 값을 반환할 뿐이지 user table에 직접 액세스 해서 유저를 찾지 않으니 모종에 이유로  user table 에는 해당 유저가 없지만 oauth table 에만 해당 유저 데이터가 남아있게 되어서 유저 존재 여부 검사를 제대로 행하지 못하면 어쩌지? 라는 생각이 들었습니다. (물론 유저를 생성할때 두 테이블에 유저정보를 생성하고, 유저를 삭제할때 두 테이블에서 유저정보를 삭제하긴 하지만요)

그래서 `findIdByOAuth` 함수를  함수 내부에서 user table과 join해서 User 객체를 반환하는 식으로 변경 한 후 (`findByOAuth` 함수로 바꿔),
User 객체에서 id 값에 액세스해 return 하는 형식으로 구조를 짜려고 합니다.
어찌보면 당연한 이야기지만 ㅎㅎ 제 생각대로 해도 되는지! 더 좋은 방법이 있을지! 궁금해서 이슈 남겨봅니다~~

**Comment by seheon99** [comment]
> user table 에는 해당 유저가 없지만 oauth table 에만 해당 유저 데이터가 남아있게 되어서 유저 존재 여부 검사를 제대로 행하지 못하면

처리하는 방법은 다양하겠지만 oauth 테이블에만 데이터가 남아있으면 로그인 실패로 이어지는게 좋을 것 같아요

> 그래서 findIdByOAuth 함수를 함수 내부에서 user table과 join해서 User 객체를 반환하는 식으로 변경 한 후 (findByOAuth 함수로 바꿔),
User 객체에서 id 값에 액세스해 return 하는 형식으로 구조를 짜려고 합니다.

해결 방법이 잘 이해가 안돼요. `findByOAuth` 를 만들려면 oauth 레포에서 찾은 유저아이디를 통해 유저 레포에서 데이터를 찾아올 수도 있고 oauth 테이블과 유저 테이블을 조인해서 한번에 유저만 찾아올 수도 있을 것 같아요. 어떤 방법을 설명하신건지 잘 모르겠지만 저는 `findByOAuth`가 레포에 있는 함수라면 `JOIN`을 사용한 SQL을 쓰는게 좋아보여용

```javascript
// users.repository.ts
async findByOAuth(provider: string, oauthId: string) {
  const result = await this.databaseService.query<User>(`
    SELECT
      'name', 'thumbnail', 'point'
    FROM
      ${this.userTable}
      INNER JOIN
      ${this.oauthTable}
    WHERE
      'oauthId'='${oauthId}'
      AND
      'provider'='${provider}'
  ;`);
  return result.length === 1 ? result[0] : null;
}
```

**Comment by happyjamy** [comment]
제가 말을 이상하게 했나봐여 findByOAuth에서 JOIN을 사용한 SQL을 써서 구조 짰다는 말이었어요 ㅎ
