### ISSUE TITLE
fix: 유저 모듈에 추가된 인증 모듈

### ISSUE THREAD

**Issue by seheon99** [SeoulGreenJacket/Dr.Trash-BE#63]
https://github.com/SeoulGreenJacket/Dr.Trash-BE/blob/f78e3d5dd78f23684b2cb526fa81ea8d4e8bb389/src/users/users.module.ts#L10-L12

이거 삭제해도될까요?

**Comment by seheon99** [comment]
@happyjamy

**Comment by happyjamy** [comment]
그거 삭제하면 circular dependency 문제 생겨요
