### ISSUE TITLE
bug:  환경변수가 undefined 떠요

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash-BE#65]
### **버그를 설명해주세요**

현재 환경 변수가 제대로 들어가고 있지 못해요.
undefined 가 떠요

**Comment by seheon99** [comment]
`ConfigModule` 을 안쓰면 안될까요

**Comment by happyjamy** [comment]
안쓰면 어떻게 할건지 설명 부탁드려요

**Comment by seheon99** [comment]
명령어 두 개를 스크립트로 만들어서 사용하면 될거같아요. 실제 환경에서는 도커컴포즈나 쿠버네티스가 설정해줘요

### 환경 변수를 설정할 때

```shell
export $(grep -v '^#' .env | xargs)
```

### 환경 변수를 해제할 때

```shell
unset $(grep -v '^#' .env | sed -E 's/(.*)=.*/\1/' | xargs)
```

https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs

**Comment by happyjamy** [comment]
만들어서 pr 올려주시면 바꿀게요~!
